gstreamer1.0-rtsp-server: depends on libcgroup and gstreamer1.0-plugins-base
Otherwise may do_compile error:
test-cgroups.c:43:23:: fatal error: libcgroup.h: No such file or directory

and:

configure: No package 'gstreamer-plugins-base-1.0' found

(From OE-Core rev: bef49e8e8bf0a7f900f4ad44c2cbb6dec1d5d180)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>